# AWS AppRunner Configuration
apiVersion: apprunner.aws.amazon.com/v1
kind: AppRunnerService
metadata:
  name: traffic-sign-api

spec:
  source:
    type: ECR
    imageRepository:
      imageName: traffic-sign-api:latest
      imageTag: latest

  instanceConfiguration:
    cpu: "1"
    memory: "2"

  autoScaling:
    minSize: 1
    maxSize: 10

  networking:
    ingressConfiguration:
      isPubliclyAccessible: true
    egressConfiguration:
      egressType: DEFAULT

  observabilityConfiguration:
    logging:
      isEnabled: true
